name: Retrain on data change
on:
  push:
    paths:
      - 'data/**'          # any file under data/ triggers
jobs:
  retrain:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: python retrain.py --csv data/new_penguins.csv --model-out penguin_auto.pkl
      - uses: actions/upload-artifact@v4
        with:
          name: retrained-model
          path: penguin_auto.pkl