name: CI
on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"          # ← all you need

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Install pytest
        run: pip install pytest

      - name: pip install with timer        # ← NEW
        run: time pip install -r requirements.txt

      - name: Run tests
        run: pytest || [ $? -eq 5 ]   # accept exit-code 5

      - name: Run tests with timer          # ← NEW
        run: time pytest
      - name: Cache info                    # ← NEW
        run: |
          echo "PIP_CACHE_DIR=$PIP_CACHE_DIR"
          du -sh $PIP_CACHE_DIR

      - name: 🧠 Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build image
        run: |
          docker build \
            --cache-from=type=local,src=/tmp/.buildx-cache \
            --cache-to=type=local,dest=/tmp/.buildx-cache-new,mode=max \
            -t myapp:latest .
          # Move cache back atomically (keeps evicted layers out)
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image
        run: docker push ghcr.io/${{ github.repository }}:latest